### ISSUE TITLE
Unable to add window -- token android.view.ViewRootImpl$W@3ddd3f5 is not val

### ISSUE THREAD

**Issue by github999999** [YummyLau/PanelSwitchHelper#127]
android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$W@3ddd3f5 is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:957)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:408)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1585)
	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1351)
	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1317)
	at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup.show(FloatingToolbar.java:733)
	at com.android.internal.widget.FloatingToolbar.doShow(FloatingToolbar.java:324)
	at com.android.internal.widget.FloatingToolbar.show(FloatingToolbar.java:251)
	at com.android.internal.view.FloatingActionMode$FloatingToolbarVisibilityHelper.updateToolbarVisibility(FloatingActionMode.java:382)
	at com.android.internal.view.FloatingActionMode$1.run(FloatingActionMode.java:67)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:230)
	at android.app.ActivityThread.main(ActivityThread.java:7809)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

**Comment by YummyLau** [comment]
fix
