### ISSUE TITLE
去了recycler_view 项目就不能运行

### ISSUE THREAD

**Issue by wanglianghai** [YummyLau/PanelSwitchHelper#3]
<android.support.v7.widget.RecyclerView
                    android:id="@+id/recycler_view"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent" /> 这个视图换成其他的就报错

**Comment by YummyLau** [comment]
> <android.support.v7.widget.RecyclerView
> android:id="@+id/recycler_view"
> android:layout_width="match_parent"
> android:layout_height="match_parent" /> 这个视图换成其他的就报错

这个是demo的代码，关联SampleActivity，替换这个布局也需要修改SampleActivity代码。具体crash贴一下log。

**Comment by wanglianghai** [comment]
07-08 15:32:46.846 19696-19696/com.example.demo D/Error: ERR: stack=java.lang.StackOverflowError: stack size 8MB
        at com.effective.android.panel.PanelSwitchHelper.access$600(PanelSwitchHelper.java:34)
        at com.effective.android.panel.PanelSwitchHelper$2.onFocusChange(PanelSwitchHelper.java:115)
        at android.view.View.onFocusChanged(View.java:6271)
        at android.widget.TextView.onFocusChanged(TextView.java:9555)
        at android.widget.EditText.onFocusChanged(EditText.java:212)
        at android.view.View.clearFocusInternal(View.java:6141)
        at android.view.View.clearFocus(View.java:6121)
        at com.effective.android.panel.view.ContentContainer.clearFocusByEditText(ContentContainer.java:118)
        at com.effective.android.panel.PanelSwitchHelper$2.onFocusChange(PanelSwitchHelper.java:110)
        at android.view.View.onFocusChanged(View.java:6271)
        at android.widget.TextView.onFocusChanged(TextView.java:9555)
        at android.widget.EditText.onFocusChanged(EditText.java:212)
        at android.view.View.handleFocusGainInternal(View.java:5997)
        at android.view.View.requestFocusNoSearch(View.java:9070)
        at android.view.View.requestFocus(View.java:9049)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3098)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3054)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3098)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3054)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3098)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3054)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3098)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3054)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3098)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3054)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3098)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3054)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3098)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3054)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3098)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3057)
        at android.view.View.requestFocus(View.java:9016)
        at android.view.View.requestFocus(View.java:8995)
        at android.view.View.rootViewRequestFocus(View.java:6170)
        at android.view.View.clearFocusInternal(View.java:6154)
        at android.view.View.clearFocus(View.java:6121)
        at com.effective.android.panel.view.ContentContainer.clearFocusByEditText(ContentContainer.java:118)
        at com.effective.android.panel.PanelSwitchHelper$2.onFocusChange(PanelSwitchHelper.java:110)
        at android.view.View.onFocusChanged(View.java:6271)
        at android.widget.TextView.onFocusChanged(TextView.java:9555)
        at android.widget.EditText.onFocusChanged(EditText.java:212)
        at android.view.View.handleFocusGainInternal(View.java:5997)
        at android.view.View.requestFocusNoSearch(View.java:9070)
        at android.view.View.requestFocus(View.java:9049)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3098)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3054)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3098)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3054)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3098)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3054)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3098)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3054)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3098)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3054)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3098)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3054)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3098)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3054)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3098)
    	at android.view.ViewGroup.requestFocus(ViewGroup.java:3
07-08 15:32:46.846 19696-19696/com.example.demo D/Error: ERR: TOTAL BYTES WRITTEN: 6650064
07-08 15:32:46.846 19696-19696/com.example.demo E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 6650148)
07-08 15:32:46.846 19696-19706/com.example.demo I/art: Background sticky concurrent mark sweep GC freed 17194(2MB) AllocSpace objects, 0(0B) LOS objects, 0% free, 38MB/38MB, paused 50.768ms total 77.638ms
07-08 15:32:46.846 19696-19696/com.example.demo E/AndroidRuntime: Error reporting crash
    android.os.TransactionTooLargeException: data parcel size 6650148 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:503)
        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:5494)
        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:96)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

**Comment by wanglianghai** [comment]
07-08 15:32:36.576 19696-19696/com.example.demo D/Panel: PanelSwitchHelper#checkoutFlag -- checkout doing : skip!
07-08 15:32:36.576 19696-19696/com.example.demo D/Panel: LogTracker#onFocusChange -- EditText has focus ( false )
07-08 15:32:36.576 19696-19696/com.example.demo D/Panel: PanelSwitchHelper#checkoutFlag -- checkout doing : skip!
07-08 15:32:36.576 19696-19696/com.example.demo D/Panel: LogTracker#onFocusChange -- EditText has focus ( false )
07-08 15:32:36.576 19696-19696/com.example.demo D/Panel: PanelSwitchHelper#checkoutFlag -- checkout doing : skip!
07-08 15:32:36.576 19696-19696/com.example.demo D/Panel: LogTracker#onFocusChange -- EditText has focus ( false )
07-08 15:32:36.576 19696-19696/com.example.demo D/Panel: PanelSwitchHelper#checkoutFlag -- checkout doing : skip!
07-08 15:32:36.576 19696-19696/com.example.demo D/Panel: LogTracker#onFocusChange -- EditText has focus ( false )
07-08 15:32:36.586 19696-19696/com.example.demo D/Panel: PanelSwitchHelper#checkoutFlag -- checkout doing : skip!
07-08 15:32:36.586 19696-19696/com.example.demo D/Panel: LogTracker#onFocusChange -- EditText has focus ( false )
07-08 15:32:36.586 19696-19696/com.example.demo D/Panel: PanelSwitchHelper#checkoutFlag -- checkout doing : skip!
07-08 15:32:36.586 19696-19696/com.example.demo D/Panel: LogTracker#onFocusChange -- EditText has focus ( false )
07-08 15:32:36.586 19696-19696/com.example.demo D/Panel: PanelSwitchHelper#checkoutFlag -- checkout doing : skip!
07-08 15:32:36.586 19696-19696/com.example.demo D/Panel: LogTracker#onFocusChange -- EditText has focus ( false )
07-08 15:32:36.586 19696-19696/com.example.demo D/Panel: PanelSwitchHelper#checkoutFlag -- checkout doing : skip!
07-08 15:32:36.586 19696-19696/com.example.demo D/Panel: LogTracker#onFocusChange -- EditText has focus ( false )
07-08 15:32:36.586 19696-19696/com.example.demo D/Panel: PanelSwitchHelper#checkoutFlag -- checkout doing : skip!
07-08 15:32:36.586 19696-19696/com.example.demo D/Panel: LogTracker#onFocusChange -- EditText has focus ( false )
07-08 15:32:36.586 19696-19696/com.example.demo D/Panel: PanelSwitchHelper#checkoutFlag -- checkout doing : skip!
07-08 15:32:36.586 19696-19696/com.example.demo D/Panel: LogTracker#onFocusChange -- EditText has focus ( false )

**Comment by wanglianghai** [comment]
好像是一直在两个函数里互相调用

**Comment by YummyLau** [comment]
> 好像是一直在两个函数里互相调用

加一下我微信 Ming_Lyan

**Comment by YummyLau** [comment]
> 好像是一直在两个函数里互相调用

feature模块的代码已经解决该问题，同时新增1.0.1版本扩展支持视频模块。
更新下依赖就可以了。
感谢提交issue
