### ISSUE TITLE
希望增加切换时的隐藏控制

### ISSUE THREAD

**Issue by MikaelZero** [YummyLau/PanelSwitchHelper#31]
demo上的效果，切换表情和键盘时，会出现短暂的表情布局变成透明  背景色会显示出来

**Comment by MikaelZero** [comment]
微信的在显示表情的情况下 切换为键盘时，是键盘直接覆盖上去，表情的布局从视觉上是可见的

**Comment by MikaelZero** [comment]
```kotlin
2020-05-29 17:27:14.385 6089-6089/com.example.demo W/System.err: java.lang.IllegalArgumentException: method android.os.SystemProperties.getInt argument 1 has type java.lang.String, got java.lang.StringBuilder
2020-05-29 17:27:14.385 6089-6089/com.example.demo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-05-29 17:27:14.385 6089-6089/com.example.demo W/System.err:     at com.effective.android.panel.utils.cutShort.XiaoMiCutShort.getInt(XiaoMiCutShort.kt:74)
2020-05-29 17:27:14.385 6089-6089/com.example.demo W/System.err:     at com.effective.android.panel.utils.cutShort.XiaoMiCutShort.hasCutShort(XiaoMiCutShort.kt:27)
2020-05-29 17:27:14.385 6089-6089/com.example.demo W/System.err:     at com.effective.android.panel.utils.CusShortUtil.getDeviceCutShortHeight(CusShortUtil.kt:33)
2020-05-29 17:27:14.386 6089-6089/com.example.demo W/System.err:     at com.effective.android.panel.device.DeviceRuntime.getDeviceInfoByOrientation(DeviceRuntime.kt:44)
2020-05-29 17:27:14.386 6089-6089/com.example.demo W/System.err:     at com.effective.android.panel.device.DeviceRuntime.getDeviceInfoByOrientation$default(DeviceRuntime.kt:29)
2020-05-29 17:27:14.386 6089-6089/com.example.demo W/System.err:     at com.effective.android.panel.view.PanelSwitchLayout.onLayout(PanelSwitchLayout.kt:296)
```

**Comment by YummyLau** [comment]
@MikaelZero log 是尝试去获取流汗的，异常可以忽略。 @MikaelZero 已经支持你说的功能了。你可以使用滑动模式。demo中聊天item超过一定就会动态切换成滑动模式，特地写成这样的。

**Comment by MikaelZero** [comment]
好的  手动点赞  非常好的库

**Comment by MikaelZero** [comment]
请问如何打开滑动模式  我看demo里的效果  都会有这个问题

**Comment by YummyLau** [comment]
@MikaelZero  构建helper的时候 .contentCanScrollOutside(true)  或者手动设置都可以，。

**Comment by MikaelZero** [comment]
可能理解错误 我录了视频

https://github.com/MikaelZero/Media/blob/master/1590751434243937.mp4

问题是这样的，当切换显示键盘时，表情部分那里的布局发生了改变

**Comment by YummyLau** [comment]
@MikaelZero 你没有开启 .contentCanScrollOutside(true) ，你可以直接打开试试。

**Comment by MikaelZero** [comment]
我在demo中的chaActivity和chatFramgent都开启了.contentCanScrollOutside(true)
还是需要在别的地方也需要设置？

**Comment by YummyLau** [comment]
@MikaelZero 加我微信吧，这样很难理解。 Ming_Lyan

**Comment by YummyLau** [comment]
@MikaelZero 我大致知道你想要的效果。之所以会这样是因为输入法会改变窗口的大小，这个是系统的调度的，而你测试出来的视频刚好那个activity我是设置了windowBackgroud的。你去掉就可以了或者你选择其他有颜色背景的fragment就可以啦。
